# Development overrides. Shared defaults remain in values.yaml.
environment: dev

web:
  replicas: 2
  image:
    tag: fd804d5073868bbf7f2e41172d82eab9b400d2a4

api:
  replicas: 1
  image:
    tag: fd804d5073868bbf7f2e41172d82eab9b400d2a4

crawler:
  replicas: 1
  image:
    tag: fd804d5073868bbf7f2e41172d82eab9b400d2a4

secrets:
  enabled: false
