{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.api.name }}
  labels:
    {{- toYaml .Values.monitoring.serviceMonitor.labels | nindent 4 }}
    {{- include "synchat.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
{{- end }}
