{{- if .Values.secrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.secretProviderClassName }}
  labels:
    app: {{ .Values.api.name }}
    {{- include "synchat.labels" . | nindent 4 }}
spec:
  provider: {{ .Values.secrets.provider }}
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "{{ .Values.secrets.objectName }}"
        objectType: "secretsmanager"
{{- end }}
