{{- if .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.api.name }}
  labels:
    app: {{ .Values.api.name }}
    {{- include "synchat.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.api.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
{{- end }}
