{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.api.name }}-ingress
  labels:
    {{- include "synchat.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.api.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.web.name }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.apiPort }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.crawler.name }}-ingress
  labels:
    {{- include "synchat.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.crawler.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.api.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.crawlerPort }}
{{- end }}
